#!/usr/bin/env python
import optparse
import sys
from collections import defaultdict
from decimal import *


getcontext().prec = 10
optparser = optparse.OptionParser()
optparser.add_option("-d", "--data", dest="train", default="data/hansards", help="Data filename prefix (default=data)")
optparser.add_option("-e", "--english", dest="english", default="e", help="Suffix of English filename (default=e)")
optparser.add_option("-f", "--french", dest="french", default="f", help="Suffix of French filename (default=f)")
optparser.add_option("-t", "--threshold", dest="threshold", default=0.5, type="float", help="Threshold for aligning with Dice's coefficient (default=0.5)")
optparser.add_option("-n", "--num_sentences", dest="num_sents", default=sys.maxint, type="int", help="Number of sentences to use for training and alignment")
(opts, _) = optparser.parse_args()
f_data = "%s.%s" % (opts.train, opts.french)
e_data = "%s.%s" % (opts.train, opts.english)

sys.stderr.write("Training with IBM Model 1..." + "\n")
bitext = [[sentence.strip().split() for sentence in pair] for pair in zip(open(f_data), open(e_data))[:opts.num_sents]]

e_keys = set()
for (k, (fs, es)) in enumerate(bitext):
  for e in es:
    e_keys.add(e)
t = defaultdict(Decimal(1/len(e_keys)))

#t = defaultdict(int)
count = defaultdict(int)
total = defaultdict(int)
s_total = defaultdict(int)
for (n, (fs, es)) in enumerate(bitext):
  for e in es:
    s_total[e] = 0
    for f in fs:
      s_total[e] += t[(e, f)]
      print(s_total[e])
      for e in es:
        for f in fs:
          count[(e,f)] += t[(f, e)] / s_total[e]
          total[f] += t[(f, e)] / s_total[e]
for (k, (f, e)) in enumerate(count.keys()):
  t[(f, e)] = count[(e, f)] / total[f]
for (fs, es) in bitext:
  for (i, f) in enumerate(fs): 
    for (j, e) in enumerate(es):
      sys.stdout.write("%i-%i-%i" % (e,f,t[(e,f)]))

"""dice = defaultdict(int)
for (k, (f_i, e_j)) in enumerate(fe_count.keys()):
  dice[(f_i,e_j)] = 2.0 * fe_count[(f_i, e_j)] / (f_count[f_i] + e_count[e_j])
  if k % 5000 == 0:
    sys.stderr.write(".")
sys.stderr.write("\n")

for (f, e) in bitext:
  for (i, f_i) in enumerate(f): 
    for (j, e_j) in enumerate(e):
      if dice[(f_i,e_j)] >= opts.threshold:
        sys.stdout.write("%i-%i " % (i,j))
  sys.stdout.write("\n")"""
